### ISSUE TITLE
binaries

### ISSUE THREAD

**Issue by steom** [wiresock/socksify#1]
please consider to release windows binaries

**Comment by wiresock** [comment]
While this remains a demonstration version and not a fully-fledged application, your convenience is our top priority. For that reason, I have incorporated a demo configuration file, specifically tailored to include essential proxy settings, making the setup process more intuitive for you. Furthermore, to ease the installation, Windows binaries have been released as part of this package. It's important to note that these enhancements were implemented with the primary intent of improving your user experience, despite the program being in its demonstration phase.
