### ISSUE TITLE
node.exe

### ISSUE THREAD

**Issue by imagecreation** [wiresock/socksify#6]
Hello! 
Thanks for a great tool!
Have one problem - 
![image](https://github.com/wiresock/socksify/assets/128193454/3211bd80-5dce-4227-8501-a8f1b316e819)
 made picrel config, but node still ignores socksify and knocks straight to the server 
![image](https://github.com/wiresock/socksify/assets/128193454/931b474b-749f-46b8-891c-52f40f3ae7bb)

Is there any solutions?

**Comment by wiresock** [comment]
Have you started ProxiFyre with Administrator privileges? Without these, the application can only access processes and connections established by the current user. Running the application as an Administrator will enable broader access.

**Comment by imagecreation** [comment]
Yes, I started it with Administrator privileges. Tried with user tho, still the same

**Comment by wiresock** [comment]
Could you please verify if Node.js is establishing outgoing connections? It's important to note that ProxiFyre can only intercept newly established connections by detecting outgoing TCP SYN packets.

**Comment by imagecreation** [comment]
![image](https://github.com/wiresock/socksify/assets/128193454/3ad2097a-e96c-482e-bc2f-9f95826c6448)
Well, as far as I can see it connects straight to servers. No my proxy IP in logs. 
I can try checking with Wireshark later, but I think it will show same behavior.

**Comment by wiresock** [comment]
Are you encountering this issue with node.exe only? Have you attempted a basic test using your browser?

**Comment by imagecreation** [comment]
I tried - browsers are working fine, as intended.

**Comment by wiresock** [comment]
Before we proceed to replicate your environment for further testing, I've introduced an improvement to ProxiFyre v1.0.13. Now you can specify the debug level as a command line parameter. If you start the application using the 'ProxiFyre all' command, it will produce detailed log output directly in the console. This could give us valuable insights to help diagnose the issue with node.exe. Could you kindly try this out and share the log with us? Your cooperation is greatly appreciated.

**Comment by wiresock** [comment]
Please note, when using the 'all' debug level, ProxiFyre not only provides detailed text logs but also captures and saves the intercepted network traffic into a pcap file for comprehensive analysis.

**Comment by imagecreation** [comment]
Sorry for confusing you, I checked with Wireshark - everything routes fine through proxy. I assume just an error with net monitoring app.

**Comment by wiresock** [comment]
Indeed, ProxiFyre operates in a fully transparent manner, which might potentially cause confusion for other applications. In actuality, the real connection is established directly from ProxiFyre itself.
